Update line number hack
Make it deal with "filenames" like `foo.rb:20:bar`.

This is common in ruby stacktraces like
```
  Traceback (most recent call last):
          4: from /usr/local/bin/irb:23:in `<main>'
          3: from /usr/local/bin/irb:23:in `load'
          2: from /usr/local/lib/ruby/gems/2.7.0/gems/irb-1.2.6/exe/irb:11:in `<top (required)>'
          1: from (irb):1
  NoMethodError (undefined method `sole' for []:Array)
```

Makes it easier to just double click and edit